version: "3.3"

services:
  frontend-admin: 
    container_name: "frontend-admin"
    image: "frontend-admin"
    build: 
      context: .
      dockerfile: Dockerfile
    links:
      - backend-api
    ports:
      - 80:3000
    restart: always
    depends_on:
      - backend-api
    networks:
      - backend-network
    environment:
      - NODE_ENV=production
# networks:
#   backend-network:
#     driver: bridge
  