version: '3.4'

services:
  frontend:
    image: frontend
    build:
      context: node_modules/lodash.uniq
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:80
